### ISSUE TITLE
Audit what the layer still hard-codes

### ISSUE THREAD

**Issue by TitusKirch** [kirchDev/duxt#14]
### Before you start

- [X] I searched existing issues and didn't find a duplicate

### What problem are you trying to solve?

The layer is deliberate about what a consumer owns: `duxtDefaults` ships no lists it cannot know, `app.config.ts` is the one file, and `mergeDuxtConfig` replaces arrays rather than appending to them. But a second class of value never went through that door — constants sitting in the module that reads them, invisible from the outside and only changeable by forking the file.

Three of them are worse than a taste difference: the "hand this page to a model" menu is fixed to ChatGPT and Claude (`app/components/DuxtCopyPage.vue:101`, `:109`), and contributor avatars are fetched from `https://github.com/<username>.png` (`app/components/DuxtPageInfo.vue:122`). A site whose docs live on GitLab gets broken images, and a site that wants a third model — or none — cannot say so.

### Proposed solution

Decide, per item, whether it becomes part of the `duxt` app.config surface or stays fixed on purpose — and record the "stays fixed" ones as a comment where they live, so the next reader does not re-open the question.

The inventory as it stands today:

| What | Where | Why it might belong to the consumer |
|:--|:--|:--|
| Model targets (ChatGPT, Claude) | `DuxtCopyPage.vue:101`, `:109` | fixed third-party services; no way to add, remove or reorder |
| Avatar host | `DuxtPageInfo.vue:122` | assumes GitHub; a GitLab-sourced site shows broken images |
| TOC depth (`h2`–`h3` only) | `app/utils/generated-toc.ts:27` | a deep reference page has no `h4` in its contents |
| Search tuning | `useFuzzySearch.ts:57`, `:61`, `:62`, `:66` | `threshold`, `minMatchCharLength`, `limit` — corpus-dependent |
| Recent pages | `useRecentPages.ts:2`, `:3` | storage key and limit of 5 |
| Toast duration | `app/components/ui/sonner/Sonner.vue:12` | 4000 ms |
| Scroll trigger | `useActiveHeading.ts:31` | 96 px, tied to a header height a consumer may change |
| OpenAPI depth | `app/utils/openapi.ts:23` (6), `DuxtOpenApiSchema.vue:37` (8) | two different numbers for the same idea |
| Draft / partial globs | `sources.ts:102`, `:116` | a repo with another convention cannot be sourced |
| Shortcut keys | `useDuxtShortcuts.ts:23` | keys collide with a consumer's own bindings |

Two things worth settling as part of it: whether the OpenAPI pair is one setting or two, and whether the shortcut list is replaceable or only extendable.

### Alternatives considered

Expose every one of them. That is the failure mode the layer already avoids elsewhere — an option nobody sets is surface that can never be removed, and each one becomes a breaking change to rename.

Leave them; a consumer forks the component. That works for the theme, and not at all for `sources.ts` or a composable — and it silently drops every later fix.

### Additional context

`docs/4.reference/1.configuration.md` is the page each accepted item lands on. The rule the layer already follows: what only the consumer can know is theirs, what the layer draws is the layer's — the three external targets fail that test outright, the rest are open.

Decided (refinement pass, 2026-09-11):

- **Model hand-off targets and the contributor-avatar URL become consumer configuration.** Model targets must support adding, removing, and ordering services; avatar configuration must not assume GitHub, so GitLab-sourced documentation can render avatars.
- **The maximum generated TOC depth becomes consumer configuration.** It defaults to the current `h3` maximum and can include `h4`.
- **Fuzzy-search tuning becomes one consumer configuration.** It covers `threshold`, `minMatchCharLength`, and the result limit, retaining today’s values as defaults.
- **The recent-pages limit becomes consumer configuration.** `0` disables the visible list; the storage key remains an internal, namespaced implementation detail.
- **The toast duration stays fixed at 4000 ms.** It is behavior of a layer-owned UI component; consumers needing different notification UX override that component rather than gaining a single-purpose configuration API.
- **The active-TOC scroll offset becomes consumer configuration.** A consumer that changes header height must be able to align active-heading detection with it.
- **OpenAPI example depth and schema-rendering depth become separate consumer settings.** They retain their current defaults of `6` and `8`, respectively, because response-size cost and browser-rendering cost are independent.
- **Draft and partial glob patterns become configurable per source.** The current `**/*.draft.md` and `**/_partials/**` patterns remain defaults, so multiple sources can retain their own conventions.
- **Shortcut bindings become a consumer-configured list that replaces the defaults.** This follows the established array semantics of `duxt` configuration and lets a consumer remove conflicting bindings as well as add alternatives.
- Supersedes the inventory’s open questions about OpenAPI depth and shortcut-list semantics.

**Comment by TitusKirch** [comment]
Implemented in e35c68b on dev.

TDD used the issue-defined seams: the public app-config defaults/replacement semantics and per-source exclusion patterns. The affected test suites pass (3 files, 1811 tests); pnpm check also passed lint, formatting, TypeScript, and Nuxt typecheck before the full suite and downstream checks.

**Comment by TitusKirch** [comment]
Review — needs human (round 1 of 3, commit e35c68b).\n\nThe implementation covers the settled consumer configuration surface (model targets, avatar template, generated TOC depth, search/recent-page controls, scroll offset, separate OpenAPI depths, per-source exclusions, and replacing shortcut lists). I found no code-level defect in the scoped commit.\n\nI cannot accept it because the required fresh-worktree gate did not complete: dependency installation, lint, formatting, and `tsc --noEmit` passed, but `pnpm check` stopped at `nuxt typecheck`. The Nuxt process guard reports that `dev --port 33545 --dotenv /tmp/duxt-env-yAhHh0/.env` (PID 182127) owns the review worktree, while that PID was no longer observable. I did not remove the guard's `.data`/database/build artifacts. Please resolve or release the owner safely, rerun `pnpm check` against e35c68b, and apply the resulting verdict.

**Comment by TitusKirch** [comment]
Re-review result: the former stale ownership block is gone, but the isolated full gate is red in `tests/nuxt-process-guard.test.ts`: the dev server returns HTTP 500 rather than 200 on initial startup. Please resolve the process-guard integration failure, then request review again.

**Comment by TitusKirch** [comment]
Re-work round 2 — pushed as `632cbc0` on `dev`.

**What the feedback asked for.** The last review found no code-level defect in the scoped work (`e35c68b`), but the isolated full gate was red in `tests/nuxt-process-guard.test.ts`: the dev server answered `/getting-started` with HTTP 500 instead of 200. That is the only thing this round changes.

**Diagnosis.** The 500 was not a process-guard defect — the guard test is simply the first thing in the suite that boots a real Nuxt dev server, so it is where a broken boot surfaces. Reproduced by hand outside vitest, the dev server aborts during module init:

```
ERROR  Cannot find module '@nuxtjs/sitemap/content'
Require stack:
- sources.ts
  at jitiResolve → sources.ts:3 → sections.ts:41 → content.config.ts:5
```

`sources.ts:3` imports `defineSitemapSchema` from `@nuxtjs/sitemap/content`, but the layer only ever declared `@nuxtjs/seo`. Under the repo's `nodeLinker: isolated`, `@nuxtjs/sitemap` exists solely as a nested dependency of `@nuxtjs/seo`, so `require.resolve` from the layer root fails and c12 cannot load `content.config.ts` at all. Nuxt's dev server still binds the port and answers every route 500 — which is exactly the symptom reported.

Two things worth flagging:

- **This is pre-existing and not caused by #14.** The import arrived in `66e105d` (*feat: say when a page last changed and who wrote it*). It is latent on a warm `node_modules` and only bites a fresh, isolated install — which is why the fresh-worktree gate is where it showed up.
- **`vitest.config.ts` was already papering over the same gap**, aliasing `@nuxtjs/sitemap/content` through `@nuxtjs/seo`'s resolution (added in `83cfebe`). That is why the suite stayed green while the dev server did not.

**Fix.** Declare `@nuxtjs/sitemap` — the package the layer actually imports — in the layer's `dependencies`. One wrinkle is recorded in the commit message: pnpm writes the root importer as the *unpeered* id `8.5.0`, for which no snapshot exists, and links a dangling symlink; the lockfile pins the peer-resolved snapshot instead. A plain `pnpm install` afterwards is idempotent and keeps the pin.

**Test discipline.** The seam came from the review feedback rather than the body: the already-failing, human-authored integration test. No seams were invented.

- *Red first*: reproduced the boot failure directly, then wrote `tests/layer-dependencies.test.ts`, which walks the `content.config.ts` import chain and asserts every external package it reaches is declared. It failed naming `@nuxtjs/sitemap (imported by sources.ts)`.
- *Green*: after declaring the dependency, that test passes and `/getting-started` returns **200** on a hand-started dev server.

The new test is the point of the round beyond the one-line fix — it turns a class of failure that previously took a 180-second dev-server test into a millisecond assertion.

**Gate.** `pnpm check` green end to end in a fresh worktree (`pnpm install --frozen-lockfile` first): lint, format, `tsc`, `nuxt typecheck`, **54/54 test files and 3263/3263 tests** — `tests/nuxt-process-guard.test.ts` included — policy parity, previews, the Nuxt production build, a11y over 12 pages, SEO over 4 pages.

`origin/dev` moved twice during the round. Rebased onto `1896bc9` before pushing, with no conflict, and re-ran lint, format, typecheck and the full suite on the rebased tree: **54/54 files, 3266/3266 tests**. The 10-minute production build was not repeated on the rebase, since the landing commit touched only `sources-git.ts` and its tests and the mutex is held across this step.

**Notes for the reviewer.**

- No config keys were added or renamed this round, so `public/devtools/config.html` needed no regeneration; `check:previews` passes (10 previews match).
- `atomic-commit` was not driven — it confirms a plan interactively and this run is unattended. Committed directly in the repo's Conventional Commits convention with the `Refs #14` trailer, which is the skill's stated fallback.
- The `@nuxtjs/sitemap/content` alias in `vitest.config.ts` is now redundant. Left in place to keep this round scoped to the feedback; removing it would make the test environment resolve the module exactly as the runtime does, and is worth a follow-up.

**Comment by TitusKirch** [comment]
Review — needs human (round 2 of 3, commits e35c68b + 632cbc0 on `dev`, branch head a6d7d80).

**The scoped work itself is sound.** Every one of the ten settled items is implemented and still wired on `dev`: `copy.models` (list-replacing, ordered, i18n-resolved through `resolveDuxtTexts`), `contributors.avatarUrl` with `{username}` substitution and no GitHub assumption, `toc.depth` (h4 now reachable) and `toc.scrollOffset`, `search.fuzzy` and `search.recentPages` (`0` empties the visible list through both callers), the separate `openapi.exampleDepth`/`schemaDepth`, per-source `exclude.drafts`/`exclude.partials`, the 4000 ms toast recorded as deliberately fixed in `Sonner.vue`, and the reference table in `docs/4.reference/1.configuration.md`. `632cbc0` correctly fixes the previous round's finding — the dev server now loads `content.config.ts` fully (all locales and versions resolve), and `tests/layer-dependencies.test.ts` turns that class of failure into a fast assertion.

**Why this is not an accept: escalation, not a request for changes.**

1. **The gate is red on the branch head, and neither failure belongs to this issue.** `pnpm check` in a fresh worktree at `a6d7d80` (after `pnpm install --frozen-lockfile`) passes lint, format, `tsc`, `nuxt typecheck`, then fails:
   - `tests/shortcuts.test.ts` — `Error: Cannot find module '/tests/shortcuts.test.ts'`, the suite never loads. Reproducible in isolation. The file was added by `f13d5ef` (#79), not by this issue.
   - `tests/nuxt-process-guard.test.ts` — 500 instead of 200. Root cause reproduced by hand: `defineMcpTool is not defined` at `server/mcp/tools/list-pages.ts:19`, an auto-import regression. That file is untouched since `40d261e`; the breakage arrived after `632cbc0`, most plausibly with `baa18d7` (package.json, a 503-line lockfile change and `www/nuxt.config.ts`). This is **not** a recurrence of the sitemap fault `632cbc0` fixed.

   Both are real defects on `dev` that this issue cannot fix, so bouncing #14 back to the implement loop would be wrong — but signing it off over a red branch would be worse.

2. **Decision 10 no longer holds on the branch, and only a human can settle that.** This issue decided "shortcut bindings become a consumer-configured list that replaces the defaults… lets a consumer remove conflicting bindings as well as add alternatives." `f13d5ef` (#79) deliberately replaced that with a policy object — `duxt.shortcuts: { singleCharacter: true }`, explicitly "no per-key override or shortcut-registration API" — with a BREAKING CHANGE note and the docs table updated to match. #79 is itself still `ai: review requested`, so the replacement is not accepted either, and neither issue body records the supersession. Closing #14 as done would record an accepted requirement the codebase contradicts.

**Two findings in this issue's own range, for whoever picks this up:**

- **`sources.ts` — the partials *include* glob silently broadened.** `exclude.partials` is now used for both the page-collection exclusion *and* the partials collection's `include`, so `definePartials` went from `_partials/**/*.md` to `**/_partials/**`. Two changes ride on that: nested `_partials/` folders are now collected (arguably a fix — they were already excluded from pages but never collected), and **non-Markdown files in `_partials/` now enter a `type: 'page'` collection**, which the `*.md` restriction introduced in `3c42609` existed to prevent. Latent today because the repo's own `_partials/` hold only `install.md`, and no test covers the include. An exclusion glob and an include glob want different breadth; consider keeping `*.md` on the include side, or documenting the conflation.
- **`DuxtCopyPage.vue` — the `UiDropdownMenuSeparator` between "View as Markdown" and the model entries was dropped unconditionally**, not made conditional on `models.length`. An unrequested visual regression riding on a configuration commit.

**What a human needs to decide:** whether #14 closes with its shortcut decision superseded by #79 (and, if so, recording that in one of the two bodies), and who owns the two branch-level gate failures above. No secrets in the diff; no CODEOWNERS and no branch protection on `dev`.

**Comment by TitusKirch** [comment]
Human verdict (2026-09-11): #79 supersedes this issue’s earlier shortcut-list decision. Return #14 to implementation only for its own follow-up findings: keep the partials collection include pattern restricted to Markdown files, and render the copy-menu separator only when model targets follow it. The unrelated shared-branch gate failures do not block this rework.

**Comment by TitusKirch** [comment]
Review — needs human (round 3 of 3, branch head `bc5a346` on `dev`).

**The round-3 rework was never pushed.** The issue moved `changes requested → working` at 21:16 on 2026-09-11 and back to `review requested` at 09:21 today, but `origin/dev` carries no commit for it: `git log origin/dev --grep '#14'` still returns exactly `e35c68b` and `632cbc0`, the two commits reviewed in rounds 1 and 2, and no implementation comment was posted for this round. No other branch on the remote carries the work either.

**Both findings the human verdict ordered are still open on the branch**, verified against `origin/dev` rather than against the commit list:

1. *Partials include still broadened beyond Markdown.* `sources.ts` sets `const PARTIALS = '**/_partials/**'` and `definePartials` uses the very same `folder.partials` value as the collection's `include` (`include: folder.partials`, and `` `${folder.path}/${folder.partials}` `` for a repository source). The exclusion glob and the include glob remain conflated, so a non-Markdown file in `_partials/` still enters a `type: 'page'` collection — the case the `*.md` restriction from `3c42609` existed to prevent.
2. *Copy-menu separator still absent.* `app/components/DuxtCopyPage.vue` contains no `UiDropdownMenuSeparator` at all; the "View as Markdown" item is followed directly by the `v-for="model in models"` items. The separator was not made conditional on `models.length`, it is simply still gone.

**What is sound, unchanged from round 2.** The settled configuration surface is still wired on the current branch head: `app/utils/duxt-config.ts` carries `copy.models`, `contributors.avatarUrl` (`{username}` template, no GitHub assumption at the call site), `toc.depth`/`toc.scrollOffset`, `search.fuzzy` and `search.recentPages`, and the separate `openapi.exampleDepth`/`schemaDepth`, with per-source `exclude.drafts`/`exclude.partials` in `sources.ts`. The shortcut item stands superseded by #79 per the human verdict of 2026-09-11.

**Why `needs human` rather than `changes requested`.** This is the third entry into review (`ai: review requested` labelled at 2026-09-11T10:18, 2026-09-11T14:49 and 2026-09-12T09:22), so `work.review.maxRounds` (3) is reached and the loop escalates instead of bouncing the issue again. The specific thing a human has to settle is why the implement round claimed the issue, held it for twelve hours and advanced it to review without pushing anything — an empty round that nonetheless consumed the last one available.

**Gate.** Not re-run against this head: the verdict does not rest on it, since the reviewed range is unchanged from round 2 and the outstanding work is absent rather than defective. The branch-level failures recorded in round 2 (`tests/shortcuts.test.ts`, `tests/nuxt-process-guard.test.ts`) were not this issue's and are not re-attributed here. No secrets in the reviewed range; no CODEOWNERS and no branch protection on `dev`.

**Comment by TitusKirch** [comment]
## The empty round has an answer — it was the drain's reconcile, not an implement round

The round-3 verdict asks a human to settle "why the implement round claimed the issue, held it for twelve hours and advanced it to review without pushing anything." No implement round did. **The label moved because of a reconcile sweep, and the sweep was wrong.**

What happened, precisely:

1. An earlier implement drain crashed while holding the single-flight lock. It left this issue on `ai: working` — that is the 21:16 transition on 2026-09-11.
2. Twelve hours later a new drain found the stale lock, reclaimed it, and ran the **implement reconcile**. That sweep classifies a `working` orphan by whether a **pushed artifact** exists: none → crashed before the push, flip back to `ready`; present → crashed after the push, advance to `reviewRequested` and finish the interrupted hand-off.
3. Under `work.branch: branch:dev` there is no pull request, so the artifact test is "the issue's commits already on the remote branch" — `git log origin/dev --grep '#14'`. That returned `e35c68b` and `632cbc0`, so the sweep read *crashed after the push* and advanced the label at 09:21.

**The test cannot distinguish the round that crashed from a round that succeeded earlier.** On a shared branch where every round tags its commits `Refs #14`, a grep is satisfied by *any* prior round. Rounds 1 and 2 had pushed; round 3 had not. The sweep saw their commits and concluded round 3's work was on the branch.

So the review is right that nothing was pushed, and right that a round was consumed — but there was no silent implementer. The round was spent by a bookkeeping step of the drain.

**The same flaw hit #12 in the same sweep**, where the review caught it one round later with the same finding ("the authorized rework had never been pushed"); there the issue still had budget and was re-worked normally. Here it took the last round.

**What this does not change:** the two findings in the verdict are real and still open on `origin/dev` — the conflated `PARTIALS` glob in `sources.ts` (exclusion and `include` share one value, so a non-Markdown file in `_partials/` still enters a `type: 'page'` collection) and the absent `UiDropdownMenuSeparator` in `app/components/DuxtCopyPage.vue`. Both want implementing.

**What it does change** is the question in front of a human: not "why did an agent do nothing for twelve hours" but "does a round lost to a faulty reconcile count against `maxRounds`?" Resetting the budget and handing this back to the implement loop would cost one round and close two small, well-specified findings.

Posted as evidence by the drain that made the mistake, not as a verdict — the escalation stands until a human resolves it.

**Comment by TitusKirch** [comment]
## Human verdict: round budget reset, back to the implement loop

The lost round was the drain's reconcile fault, not an implement round's, so it does not count against `work.review.maxRounds`. The two findings stand and are to be implemented:

1. `sources.ts` — the `PARTIALS` exclusion glob and the collection `include` share one value, so a non-Markdown file under `_partials/` still enters a `type: 'page'` collection. Restore the `*.md` restriction the exclusion needs without narrowing what `definePartials` includes.
2. `app/components/DuxtCopyPage.vue` — the `UiDropdownMenuSeparator` between "View as Markdown" and the model items is absent. Restore it, conditional on `models.length`.

**Comment by TitusKirch** [comment]
## Round 4 — both outstanding findings implemented on `dev`

Commits `0dd4e69` and `e02ea0a`, pushed to `origin/dev` (`fe6086e..e02ea0a`).

**1. `sources.ts` — the two globs are separated.** `exclude.partials` stays what a consumer sets and what the page collections exclude: the whole `_partials/` subtree, every file in it, whatever the extension. The partials collection's own `include` is now derived from it by `partialsInclude`, which restores the `*.md` restriction `3c42609` wrote and `e35c68b` lost. Nothing `definePartials` legitimately includes is narrowed — every Markdown file the subtree holds, at whatever depth the consumer's glob reaches, still lands in the collection, and a glob that already names files (`**/_partials/**/*.mdc`) is returned untouched.

Derivation, three rules: a glob whose last segment carries an extension is left alone; one ending `**` gains `/*.md`; one ending `*` gains `.md`; a bare folder gains `/**/*.md`. So the default `**/_partials/**` yields `**/_partials/**/*.md` — byte-for-byte the value that stood before the setting became configurable — and a repository source yields `docs/**/_partials/**/*.md`.

**2. `DuxtCopyPage.vue` — the separator is back**, as `<UiDropdownMenuSeparator v-if="models.length" />` between the "View as Markdown" item and the `v-for` model items. Guarded so an empty `copy.models` does not leave a rule drawn under the last item with nothing beneath it.

**Test discipline.** The seams came from the human verdict of 2026-09-12, which named both findings precisely. Finding 1 is code with a seam a test reaches, so `tests/sources-collections.test.ts` gains a `describe` block that was driven red first: with `definePartials` reverted to the conflated value, 5 of its cases fail (`expected '**/_partials/**' to be '**/_partials/**/*.md'` and the custom-glob variants); with the fix in place all 18 in the file pass. It covers the local source, a repository source and four consumer glob spellings, asserting in each that the page collection still excludes the whole subtree while the partials include is Markdown-restricted. Finding 2 is a template change in a component the repo deliberately does not unit-test (no Nuxt environment; SSR failures are what `build:app` catches) — it is covered by the gate's build, not by a new test.

**Gate.** `pnpm check` green in full — lint, format, both typechecks, `vitest` (all suites), `check:policy`, `check:previews`, `build:app`, `check:a11y` (15 pages), `check:seo` (4 pages), `check:images` (6 images).

**Scope.** Only the two findings. No documentation change: `docs/4.reference/1.configuration.md` documents `exclude.partials` as the subtree glob with default `**/_partials/**`, which is still exactly what the setting is.

**Comment by TitusKirch** [comment]
Review — accepted (round 4, commits `0dd4e69` + `e02ea0a` on `dev`, branch head `7db5a0e`).

**Both findings the human verdict of 2026-09-12 ordered are implemented, and verified against `origin/dev` rather than against the commit messages.**

1. **`sources.ts` — the two globs are separated.** `PARTIALS` stays `**/_partials/**` and is still what the page collections exclude, so the whole subtree is lost to them whatever the extension. `definePartials` no longer passes that value as its own `include`: it derives one through the new `partialsInclude`, and both call sites use it — `include: partialsInclude(folder.partials)` for a local source and `` `${folder.path}/${partialsInclude(folder.partials)}` `` for a repository one. The default now yields `**/_partials/**/*.md`, restoring the `*.md` restriction `3c42609` wrote and `e35c68b` lost, so a screenshot beside a partial can no longer enter a `type: 'page'` collection. The four derivation rules are sound on the spellings that matter: a glob already naming files is returned untouched, one ending `**` gains `/*.md`, one ending `*` gains `.md`, a bare folder gains `/**/*.md`. Nothing legitimately included is narrowed. The `describe` block added to `tests/sources-collections.test.ts` asserts exactly the pair the finding was about — the page collection still excluding the whole subtree while the partials include is Markdown-restricted — across a local source, a repository source and four consumer glob spellings.

2. **`DuxtCopyPage.vue` — the separator is back and correctly bound.** `<UiDropdownMenuSeparator v-if="models.length" />` sits between the "View as Markdown" item and the `v-for` model items, with `models` resolving to `duxt.copy?.models ?? []`. The guard is the one the verdict asked for: an empty consumer list draws no rule under the last item. `DropdownMenuSeparator.vue` exists in `app/components/ui/dropdown-menu/`, so the prefixed component resolves.

**The rest of the settled surface is unchanged and still wired** on the branch head — `copy.models`, `contributors.avatarUrl` with its `{username}` template, `toc.depth`/`toc.scrollOffset`, `search.fuzzy`, `search.recentPages`, the separate `openapi.exampleDepth`/`schemaDepth`, per-source `exclude.drafts`/`exclude.partials`, and the 4000 ms toast recorded as deliberately fixed. `docs/4.reference/1.configuration.md` still documents `exclude.partials` as the subtree glob with default `**/_partials/**`, which remains precisely what the setting is — the include derivation is internal and needs no documentation change. The shortcut item stands superseded by #79 per the human verdict of 2026-09-11.

**Gate — green end to end, and that is the change from rounds 2 and 3.** `pnpm check` run in a throwaway worktree at `7db5a0e` after `pnpm install --frozen-lockfile`: lint, format, `tsc --noEmit`, `nuxt typecheck`, **82/82 test files and 4021/4021 tests**, policy parity, 10 devtools previews, the Nuxt production build, a11y over 15 pages, SEO over 4 pages, images over 6. Exit code 0. Both failures that forced the round-2 escalation are resolved on the branch: `tests/shortcuts.test.ts` loads and passes, and `tests/nuxt-process-guard.test.ts` passes — the `defineMcpTool is not defined` regression is gone.

**One pre-existing red, not attributed here.** The `Adapters` workflow fails on `7db5a0e`, but it has failed continuously since 2026-09-11 and is already red on `fe6086e`, the parent of this round's first commit. It is deliberately outside `pnpm check` (a build per adapter, and a server for PostgreSQL). `CI` and `CodeQL` are green on the head. No secrets in the reviewed range; no CODEOWNERS and no branch protection on `dev`.

**Why accept rather than escalate.** The round budget was reset by the human verdict of 2026-09-12 after the reconcile-induced empty round, and the two findings that reset was granted for are both closed, with the gate that was red for two rounds now green. The prior escalation was lifted by a human and the work no longer fails, so escalating again would be wrong.
