### ISSUE TITLE
Document which Content database adapters pass through

### ISSUE THREAD

**Issue by TitusKirch** [kirchDev/duxt#35]
### Before you start

- [x] I searched existing issues and didn't find a duplicate

### What problem are you trying to solve?

Content v3 runs on five database adapters — `sqlite`, `d1`, `postgresql`, `libsql` (Turso) and `pglite`. duxt exercises exactly two: `node:sqlite` locally and D1 on Workers, both of them in `www/`. For the other three, nobody has established whether the layer is transparent or whether it quietly assumes a filesystem.

There is a concrete reason to doubt it. `content-cache.ts` opens `.data/content/contents.sqlite` **directly**, with `node:sqlite`, bypassing Content's adapter entirely — that is what the build validator, `duxt-report` and the section reports read. It is build-time code and therefore probably fine on any deploy target, but "probably" is the current state of the answer, and a consumer who deploys to Turso or Postgres finds out for themselves.

This is a documentation gap rather than a missing feature, and the deliverable should say so honestly if that is what it turns out to be.

### Proposed solution

Establish and then document which adapters pass through the layer untouched.

- **Prove it.** Build `www/` (or a minimal consumer) against `libsql` and `postgresql` and confirm the site renders, the three dynamic endpoints answer, and `duxt-report` still runs.
- **Name what is build-time-only.** `content-cache.ts`, `modules/git-meta.ts` and the report path all touch the filesystem. Say plainly that they run during the build and never on the deployed server, which is what makes a Worker or a serverless target possible at all.
- **Write it down** as a docs page beside the existing deployment prose — one short table of adapter, what it needs installed, and whether duxt has been seen to work on it, with the untested ones marked untested rather than implied to work.
- **Record what the layer must never do**: read the content database at runtime through anything but `queryCollection()`.

### Alternatives considered

- **Claim support for all five without testing.** Rejected — that is exactly the kind of claim a documentation layer must not make about itself.
- **Ship an adapter option in the layer's own config.** Rejected: the adapter is the consuming site's deployment decision and Content already owns the surface. The layer's job is to not get in the way.

### Additional context

- Content's adapter documentation: https://content.nuxt.com/docs/getting-started/configuration
- The Workers case is already settled and written up in `CLAUDE.md` — D1, `nodejs_compat`, and the fact that only `/mcp`, the `.md` middleware and the demo endpoint ever read the binding.

Decided (refinement, 2026-09-11):

- **`libsql` and PostgreSQL stay covered by CI after their initial proof.** Each check verifies the build, the three dynamic endpoints and `duxt-report`, so the documented compatibility cannot silently regress.
- **PGlite remains documented as untested** until it receives an equivalent dedicated proof and CI coverage.

**Comment by TitusKirch** [comment]
## Implemented on `dev` — `baa18d7`

Shared-branch strategy (`work.branch = branch:dev`), so there is no PR; the commit is on `dev`.

### What the investigation actually found

The doubt in the issue body was that `content-cache.ts` opens `.data/content/contents.sqlite` directly with `node:sqlite`, bypassing Content's adapter. That is real, and it is **not** a portability problem, because Content keeps **two** databases and they are different types:

| | `content._localDatabase` | `content.database` |
| :--- | :--- | :--- |
| Holds | The parse cache, in `.data/content/` | The collections the site queries |
| Lives | During a build | On the deployed server |
| Typed | `SqliteDatabaseConfig \| D1DatabaseConfig` — nothing else | any of the five adapters |

Read off `@nuxt/content@3.16.0` (`dist/module.d.mts:550`, default at `dist/module.mjs` `moduleDefaults._localDatabase`). `content-cache.ts`, `modules/git-meta.ts` and `duxt-report` all read the **first**, so no adapter choice moves them. The layer is transparent to all five adapters for exactly one reason: it reads the deployed database only through `queryCollection()`.

### Proof, not assertion

`www/` was built against each adapter and probed:

| Adapter | Build | Page | `…/page.md` | `/llms.txt` + `/llms-full.txt` | `POST /mcp` `list_pages` | `duxt-report` | DB state |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| `libsql` | ok | ok | ok | ok | ok | exit 0, 0 errors | 33 tables, 140 rows in `_content_docs` (22 MB file) |
| `postgresql` | ok | ok | ok | ok | ok | exit 0, 0 errors | 33 tables, 140 rows in `_content_docs` |

`duxt-report` was green on both while the deployed database was *not* SQLite — which is the claim about the build-time cache, demonstrated rather than argued.

One real defect surfaced and was fixed during the proof: a relative `file:` libsql URL is opened against the **server's** working directory and libsql does not create the parent directory, so `file:.data/content/libsql.db` died with `Unable to open connection … : 14` (SQLITE_CANTOPEN). The config now computes an absolute path under `tmpdir()`.

### Test discipline

The change touches code, so `tdd` was driven on the one seam the body yields — *"Record what the layer must never do: read the content database at runtime through anything but `queryCollection()`."* That is an invariant, so it became an enforced test rather than prose:

`tests/content-database.test.ts` — **proven red before green**, twice, against deliberately planted violations:
- a `node:sqlite` import added to `server/routes/llms.txt.get.ts` → *"server/routes/llms.txt.get.ts imports node:sqlite"*, 2 assertions red;
- a `contents.sqlite` reference in the same file → the cache-file assertion red.

Both plants reverted (`git diff server/` clean) before commit.

The rest of the change is prose (five docs pages) and CI wiring, which `tdd` does not reach.

### Delivered

- `docs/2.concepts/11.databases.md` + `de`/`es`/`fr`/`pt` — the two databases, the adapter table, what is build-time-only, and the rule. **PGlite is marked untested**, per the refinement decision, not implied to work.
- `tests/content-database.test.ts` — the rule, enforced; keeps the list of build-time files that may open a database closed.
- `scripts/check-adapters.ts` (`pnpm check:adapters`) — probes the endpoints that read the database at runtime, including a full MCP streamable-HTTP session so the tool call actually reaches a collection.
- `.github/workflows/adapters.yml` — `libsql` + `postgresql` matrix on every PR, so the documented compatibility cannot silently regress.
- `CLAUDE.md`/`AGENTS.md` updated (byte-identical, `diff` clean).

### Two things a reviewer should weigh

1. **`check:adapters` is deliberately not in `pnpm check`.** Each leg is a second full Nuxt build and the PostgreSQL one needs a server, so it runs as a parallel matrix workflow instead. This is the first check in the repo that does *not* arrive by adding a line to `package.json`, and it is stated as such in `CLAUDE.md`.
2. **`@libsql/client` and `pg` are now `www/` devDependencies.** `CLAUDE.md` previously said `www/` builds "with neither present". That sentence was amended rather than left to rot: nothing imports either, an ordinary build loads neither, and they exist only so the matrix can build against those adapters.

### Verification

`pnpm check` green twice — once on the work alone, and again after a `pnpm-lock.yaml` rebase conflict with `632cbc0` (`Refs #14`) was resolved by regenerating the lockfile from the merged manifests (both intents verified present; `--frozen-lockfile` passes). 56 test files pass, a11y and SEO both green.

**Comment by TitusKirch** [comment]
## AI review — round 1 of 3 · needs human

Reviewed commit `baa18d7` (`Refs #35`), the only commit on `dev` for this issue. Shared-branch strategy, so there is no PR; the gate was re-run independently in a throwaway worktree at `origin/dev` (`3565678`).

### The work itself: correct and complete

Every requirement in the body is met, and the refinement decisions are honoured.

- **"Prove it."** `www/` is buildable against `libsql` and `postgresql`, and the proof is reproducible rather than a claim in a comment: `scripts/check-adapters.ts` probes the four surfaces that actually read the deployed database — the `…/page.md` middleware, `/llms.txt`, `/llms-full.txt` and a full MCP streamable-HTTP session ending in a `tools/call` on `list_pages`. Probing the tool call rather than `initialize` is the right choice; an `initialize` alone is answered by the transport and proves nothing about a collection.
- **"Name what is build-time-only."** The two-databases distinction (`content._localDatabase`, typed `sqlite | d1`, versus `content.database`) is the real answer to the doubt the body raised about `content-cache.ts`, and it is stated in the docs page, in `CLAUDE.md` and in the commit message.
- **"Write it down."** `docs/2.concepts/11.databases.md` plus `de`/`es`/`fr`/`pt`, all genuine translations with matching frontmatter. The adapter table marks **PGlite untested**, per the refinement decision, with a callout saying nothing is known to be wrong *or* right with it. `/guides/deploy-a-site` resolves (`docs/3.guides/6.deploy-a-site.md`) and matches the house link style.
- **"Record what the layer must never do."** Turned into `tests/content-database.test.ts` rather than prose — 5 assertions, all passing in isolation. The design is good: it refuses any driver import under `server/`/`app/` outright, keeps a closed allowlist of build-time files each carrying a written reason, and guards itself with a "did the walk actually find anything" assertion, which is the one failure mode an allowlist test cannot otherwise report.
- **CI coverage after the proof**, per the refinement: `.github/workflows/adapters.yml` runs build + endpoint probe + `duxt-report` per adapter, `fail-fast: false`, PostgreSQL started as a step rather than a job-level service so the libsql leg does not wait on it. `fetch-depth: 0` for `modules/git-meta.ts` is a real detail correctly caught.

Also checked and clean: `diff CLAUDE.md AGENTS.md` is empty; `scripts/` is correctly absent from the `files` allowlist so nothing new is published; the libsql absolute-`file:`-path fix in `www/nuxt.config.ts` is guarded behind `DUXT_CONTENT_ADAPTER` so an ordinary build takes the unchanged `{}` branch; no secrets (the matrix PostgreSQL credentials belong to a throwaway container). The `@libsql/client`/`pg` devDependency addition was disclosed rather than left to contradict the existing `CLAUDE.md` sentence.

### Why this is not `done`

`pnpm check` is **red at `origin/dev`**, and a review may not accept on a gate it could not establish green. Three independent failures, and **none of them touches this issue's commit range**:

1. `tests/shortcuts.test.ts` — `Error: Cannot find module '/tests/shortcuts.test.ts'`, a whole suite failing to load. The file exists and is committed; it fails in isolation too. Introduced by `f13d5ef` (`feat(shortcuts)!: make global keyboard shortcuts configurable`).
2. `tests/nuxt-process-guard.test.ts > keeps serving when a .env change restarts Nuxt dev` — `expected 500 to be 200`, matcher timeout after ~180s. Lineage `db6f910` / `4410bec` / `d51c391`.
3. `pnpm build:app` — `ERROR defineMcpTool is not defined` during the prerender, from `nitro.mjs`. The symbol is an auto-import used by the four `server/mcp/tools/*.ts` files; `git log -S` attributes the current shape to `40d261e` (`feat(mcp): deepen the documentation interface`), two commits before HEAD. **This is the most serious of the three** — the SSR gate does not complete at all, so `check:previews`, `check:a11y` and `check:seo` never ran on this head either.

Per the shared-branch attribution rule, a red that this issue's diff does not explain is a real finding that this issue cannot fix, so it escalates rather than bouncing work whose own diff is fine. #35's own test file passes; its changes are not implicated in any of the three.

**What a human is asked to decide:** whether to accept #35 on its merits and track the three branch failures separately (particularly the `defineMcpTool` prerender break, which currently leaves `dev` unbuildable), or to hold this issue until `dev` is green again.

### One non-blocking observation

`adapters.yml` triggers on `pull_request` into `main`/`dev` and on `push` to `main`. This repo's implement loop commits **directly to `dev`**, so on the normal path the matrix first runs at the `dev → main` promotion PR, not per change. That still gates everything before `main` — and it matches `ci.yml`'s own trigger set — but it is a weaker "cannot silently regress" than the docs prose implies. Worth a sentence, not a change.

**Comment by TitusKirch** [comment]
Human verdict (2026-09-11): accepted on its merits. The previously observed shared-branch gate failures are unrelated to #35 and must be tracked separately; they do not block this issue.
